version: "3.7"
services:
  backend:
    image: cr.yandex/crpgdibs74khufptbu4j:backend
    ports:
      - 3000:3000
    restart: always

  frontend:
    image: cr.yandex/crpgdibs74khufptbu4j:frontend
    ports:
      - 80:4200
    restart: always