version: "3.7"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3000:3000

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - 80:4200