name: ci/cd

on:
  push:
    branches: ['master']
env:
  CR_REGISTRY: crpgdibs74khufptbu4j
  IMAGE_TAG_FRONTEND: frontend
  IMAGE_TAG_BACKEND: backend
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  update-yc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy COI VM
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy@v1.0.1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: 'b1g9u079h6hri0udbrmt'
        VM-name: 'tested'
        vm-service-account-id: 'ajeaorne25djejr6ile9'
        vm-cores: 2
        vm-platform-id: 'standard-v2'
        vm-memory: 512Mb
        vm-disk-size: 30Gb
        vm-core-fraction: 5
        ssh-key: ~/.ssh/id_rsa.pub
        vm-subnet-id: 'e9bu7ur6f08ojuln8q4e'
        docker-compose-path: './docker-compose.yaml'
        user-data-path: './user-data.yaml'
